#user inputs sorted by order not type
year = input ("Enter a year. ")
city = input ("Enter a city. ")
cafe = input ("Enter the name of a restaurant. ")
animal_1 = input ("Enter an animal. ")
song = input ("Enter the title of a song. ")
person_1 = input ("Enter the name of a person. ")
animal_2 = input ("Enter another animal. ")
person_2 = input ("Enter another persons name. ")
emotion = input ("Enter an emotion. ")
smell = input ("Enter a smell. ")
sound = input ("Enter a sound/noise. ")
color_1 = input ("Enter a color. ")
color_2 = input ("Enter another color. ")
number_1 = input ("Enter a number between 1 and 10. ")
number_2 = input ("Enter a number between 10 and 25. ")

#unused user inputs
#adjective = input ("Enter an adjective. ")
#verb = input ("Enter a verb. ")
#noun = input ("Enter a noun. ")
#user_name = input ("Enter your name. ")
#preposition = input ("Enter a preposition. ")
#adverb = input ("Enter an adverb. ")

#beginnning of mad lib:
print("The year is", year, "you're walking down the street in ", city, ". You are on your way to meet up with some friends at", cafe, ".")
print("You arrive at", cafe, "to see that none of your friends are there and instead there is an army of", animal_1, ".")
print("You continue to approach the mob of", animal_1, "and as you get closer and closer", song, "starts to play in the background and rise in volume.")
print("When you get even closer you see your friend", person_1, "standing in the middle of the mob. They start to flag you over to them. You get into talking distance of them and as you start talking a pop of smoke appears under them and they dissapear. When the smoke clears all that is left is a(n)", animal_2, "you look closer to see that the", animal_2, "is wearing a nametag saying your friends name.")
print("You start to read the nametags on other animals and see", person_2,"'s name printed on one of the collars.")
print("You start to feel ", emotion, "and wonder if you are going to turn into an animal aswell.")
print("As the crowd around the animals grows so does the amount of animals, people are turning into animals left and right and the air is continuously filling with the smell of ", smell, "You ponder how this is happening.")
print("One of the smoke bombs plops by your feet and you hear a loud", sound, "Your eyes fill with smoke and when it clears the entire world is tinted", color_1, "You let out a scream but it comes out as quiet moo.")
print("You transformed into a cow, you try to reach for you phone that is sitting on the ground next to you but come to the realization that you have hooves.")
print("You look up again to see", person_2, "looking at you.")
print(person_2, "wears a tophat that looks ", color_2, "with the ", color_1, "tint you see the world through.")
print(person_2, "says to you in a series of moos how in exactly ", number_1, "seconds everyone here would turn back to normal.")
print(number_2, "seconds go by and you turn back to normal. You and ", person_2, "look at eachother and shrug just glad to be back. ")